### ISSUE TITLE
TODO Discussion

### ISSUE THREAD

**Issue by 3y3** [node-inspector/v8-profiler#33]
- [x] Update API to V8 3.22 (backward compatible where is possible). Using [nan](https://github.com/rvagg/nan)
- [x] Notify to issues, that v8-profiler starts resurrection, check closed issues.
- [x] Add travis build
- [x] Collect experience from
 - NodeFly / nodefly-v8-profiler
 - skomski / v8-profiler
- [x] Check HeapGraph API
- [x] Add tests
- [x] Add prebuild binaries

**Comment by yorkie** [comment]
Hey @3y3 how is the HeapGroup API going now? Just question :)

**Comment by 3y3** [comment]
Are you mean `HeapGraph` API or I missed something new in v8?

**Comment by yorkie** [comment]
Ah...yeah, just my typo, haha, sorry

**Comment by 3y3** [comment]
Heap Graph API completely implemented. I just missed to close this issue. Thanks for targeting.

**Comment by yorkie** [comment]
:)
